runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /slick
  static_dir: templates/slick
- url: /js
  static_dir: templates/js
- url: /css
  static_dir: templates/css
- url: /images
  static_dir: images/
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest


skip_files:
- node_modules/
- .git/
